### PR TITLE
Merge branch 'master' into updates_JD

### PR DESCRIPTION
**Pull request by JeanDidier**
Some updates.

### CODE REVIEW

**Comment by JeanDidier** [comment]
He hecho otro pulll.....

Dr. Jean-Didier Maréchal
Associate Professor
Committee Member and Spanish representative COST Action CM1306 - Molecular
Machinery
Adjunct Course Director in B. Sc. in Chemistry (UAB)
Adjunct Course Director in Master in Bioinformatics (UAB)
Cites previes a: http://cita.uab.cat/ciencies/dept-quimica/marechal/

Insilichem
Departament de Química
Universitat Autònoma de Barcelona
Edifici C.n.
08193 Cerdanyola (Barcelona)
Tel: +34.935814936
e-mail: JeanDidier.Marechal@uab.es
www: http://www.inslichem.com

2016-10-27 15:27 GMT+02:00 Jean-Didier Maréchal <
jeandidier.marechal@gmail.com>:

**Comment by jaimergp** [comment]
No hay cambios... o0

**Comment by JeanDidier** [comment]
euh, no sale lo nuevo...mierda.

Dr. Jean-Didier Maréchal
Associate Professor
Committee Member and Spanish representative COST Action CM1306 - Molecular
Machinery
Adjunct Course Director in B. Sc. in Chemistry (UAB)
Adjunct Course Director in Master in Bioinformatics (UAB)
Cites previes a: http://cita.uab.cat/ciencies/dept-quimica/marechal/

Insilichem
Departament de Química
Universitat Autònoma de Barcelona
Edifici C.n.
08193 Cerdanyola (Barcelona)
Tel: +34.935814936
e-mail: JeanDidier.Marechal@uab.es
www: http://www.inslichem.com

2016-10-27 14:59 GMT+02:00 Jaime RGP notifications@github.com:

**Comment by JeanDidier** [comment]
He vuelto a hacer un pull request y yo si que veo cambios. Tendria que
funcionar ahora. #9

Dr. Jean-Didier Maréchal
Associate Professor
Committee Member and Spanish representative COST Action CM1306 - Molecular
Machinery
Adjunct Course Director in B. Sc. in Chemistry (UAB)
Adjunct Course Director in Master in Bioinformatics (UAB)
Cites previes a: http://cita.uab.cat/ciencies/dept-quimica/marechal/

Insilichem
Departament de Química
Universitat Autònoma de Barcelona
Edifici C.n.
08193 Cerdanyola (Barcelona)
Tel: +34.935814936
e-mail: JeanDidier.Marechal@uab.es
www: http://www.inslichem.com

2016-10-27 17:42 GMT+02:00 Jaime RGP notifications@github.com:

**Pull request merged**
